In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('HouseTS.csv')
us_metros = pd.read_csv('usmetros.csv')

In [3]:
df.head(4)

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,...,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,...,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,...,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,Atlanta-Sandy Springs-Alpharetta
2,2012-05-31,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,...,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,Atlanta-Sandy Springs-Alpharetta
3,2012-06-30,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,...,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,Atlanta-Sandy Springs-Alpharetta

In [4]:
us_metros.head()

,metro_fips,metro,metro_ascii,metro_full,county_name,county_fips,state_id,state_name,lat,lng,population
0,35620,New York,New York,"New York-Newark-Jersey City, NY-NJ",Suffolk,36103,NY,New York,40.7222,-74.0225,19940274
1,31080,Los Angeles,Los Angeles,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles,6037,CA,California,34.2215,-118.1494,12927614
2,16980,Chicago,Chicago,"Chicago-Naperville-Elgin, IL-IN",Cook,17031,IL,Illinois,41.6675,-87.9597,9406924
3,19100,Dallas,Dallas,"Dallas-Fort Worth-Arlington, TX",Denton,48121,TX,Texas,32.8495,-96.9704,8344032
4,26420,Houston,Houston,"Houston-Pasadena-The Woodlands, TX",Harris,48201,TX,Texas,29.8422,-95.3855,7796182

In [5]:
df['date'] = pd.to_datetime(df['date'])
print (df['date'].dt.year.value_counts())

date
2013    74712
2014    74712
2015    74712
2016    74712
2020    74712
2017    74712
2018    74712
2019    74712
2022    74712
2021    74712
2023    74712
2012    62260
Name: count, dtype: int64

### To avoid Leakage: The test set will run from 2012-2018
### The Eval Set will run from 2018-2022 and is unseen
### Holdout set will be from 2022 -2023

In [6]:
df = df.sort_values('date')

In [7]:
cut_off = '2020-01-01'
hold_out = '2022-01-01'

In [8]:
### The training data should run from '12 to '18
train_df = df[df['date'] < cut_off]

In [9]:
### The test data is between '18 and '22
test_df = df[(df['date'] > cut_off) & (df['date'] < hold_out)]

In [10]:
### The holdout data is after '22
holdout_df = df[df['date'] > hold_out]

In [11]:
train_df.shape

(585244, 39)

In [12]:
test_df.shape

(149424, 39)

In [13]:
holdout_df.shape

(149424, 39)

In [14]:
###Saving to CSV
train_df.to_csv('Train Set.csv', index = False)
test_df.to_csv('Test Set.csv', index = False)
holdout_df.to_csv('HoldOut Set.csv', index = False)